name: example-for-repository-using-this-action

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: write

    steps:
      - uses: hexlet-college-students/transcrypt-actions@main
        with:
          PASSWORD: ${{ secrets.TRANSCRYPT_PASSWORD }}
        name: decrypting-action

      - run: make install
      - run: make lint
      - run: make test